// This file is generated by Astro DB
declare module 'astro:db' {
	export const Comment: import("@astrojs/db/runtime").Table<
		"Comment",
		{"authorId":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"authorId","collection":"Comment","primaryKey":false,"optional":false}},"body":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"body","collection":"Comment","primaryKey":false,"optional":false}}}
	>;
	export const Author: import("@astrojs/db/runtime").Table<
		"Author",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Author","primaryKey":false,"optional":false}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Author","primaryKey":false,"optional":false}}}
	>;
}
