// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "standardActions",
    columns: [
      { name: "created_at", type: "string" },
      { name: "title", type: "string" },
      { name: "phase_number", type: "int" },
      { name: "phase_name", type: "string" },
      { name: "standard_action_description", type: "text" },
      { name: "modifier", type: "string" },
      { name: "standard_action_condition", type: "string" },
      { name: "description_phase_title", type: "string" },
      { name: "standard_action_tag", type: "string" },
      { name: "Spending_Cost", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type StandardActions = InferredTypes["standardActions"];
export type StandardActionsRecord = StandardActions & XataRecord;

export type DatabaseSchema = {
  standardActions: StandardActionsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Matthew-Morrison-s-workspace-sscbmm.us-east-1.xata.sh/db/Beacon-Companion",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
